### ISSUE TITLE
Clarify COLRv1 allocation bounds to originate from glyph contour points

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/colr-gradients-spec#209]
In the processing pseudo code, I read

- "Allocate a bitmap for the glyph according to glyf table entry extents for gid"

(I thought I understood it's like this for COLRv0, too, although I can't find it in the current spec.)

This is not ideal (why should the bounds of the fallback glyph be equal or bigger than the corresponding color glyph?), but it feels "less than ideal" if we want to see COLRv1 as "glyf2", as the notion of a fallback glyph makes little sense there.

I know the bounding box values for glyf glyphs can lie, but that doesn't seem very nice, either. Or is that precisely what should be done here?

I can't find any discussion about this in the spec document.

**Comment by PeterConstable** [comment]
For COLR v0, advance width/height of the colour glyph must be that of the base glyph. This is stated in the current [OT COLR spec](https://docs.microsoft.com/en-us/typography/opentype/spec/colr), and in the draft in 5.7.11.1.8.1. The bounds for v0 formats aren't an issue since each glyph in each layer is drawn using it's glyf entry.

For COLR v1, the advance width/height must be derived from something, and it's spec'd the same as for v0: the metrics of the base glyph are used (first paragraph of 5.7.11.1.8.2). Unlike v0, bounds are an issue for v1 formats since it's no longer a simple matter of drawing one glyph per layer, but of composing graphic operations onto a surface. A graph of v1 paint tables could potentially describe an unbounded graphic, and the fourth paragraph of 5.7.11.1.8.2 constrains this—the graph must be bounded. But that still leaves an issue of efficiently determining what the bounds are so that a surface can be allocated. If nothing further were stated, it would imply that the graph must be traversed and computed to determine the bounds before any actual paint operations could be performed (or else risk costly re-allocations during paint operations). To allow for more efficient processing, the draft spec states that the maximal bounds can be determined up front by using the bounding box of the base glyph—second paragraph of 5.7.11.1.8.2, and following note.

**Comment by justvanrossum** [comment]
Ahh, thanks for the pointers, I somehow managed to not search in that part of the spec, my apologies.

Ok, but that leaves me one question, esp. after reading this sentence:

"The bounding box of the base glyph is used as the bounding box of the color glyph. A 'glyf' entry with two points at diagonal extrema is sufficient to define the bounding box."

When it says "bounding box", does it mean the (control) bounding box of the actual shape stored in the glyf table, or does it mean to look at the xMin, yMin, xMax and yMax values of the base glyph?

Also, how is this supposed to work for CFF base glyphs? It appears that this makes COLRv1 incompatible bith CFF/CFF2.

I understand the need for knowing the bounding box up front, but perhaps it's better if COLRv1 glyphs define their own bounding boxes?

**Comment by justvanrossum** [comment]
...or perhaps it should be reworded so that it includes CFF/CFF2, and that the bounding box should be derived from the shape, even in the case of glyf, as variations may obviously invalidate glyf xMin, yMin, xMax, yMax bounding box values.

**Comment by anthrotype** [comment]
> When it says "bounding box", does it mean the (control) bounding box of the actual shape stored in the glyf table, or does it mean to look at the xMin, yMin, xMax and yMax values of the base glyph?

I think it means the control bounding box of the actual glyf shape rather than the nominal bbox values as stored in the glyf entry. We can add wording to clarify that, if not already.

/cc @drott

**Comment by anthrotype** [comment]
if the actual bounding box of the glyf shape that correspond to a COLRv1 base glyph happens to be too tight and does not contain all the color layers (e.g. if it's designed as the B/W fallback glyph to be displayed when no COLR support exist), then a solution would be to add two invisible single points (open contours containing a single move point thus unfillable and not visible) at the extreme points of the desired bounding box such that they fully enclose the colored shape as well.

**Comment by justvanrossum** [comment]
It should be possible to have contours consisting of a single point, but open contours exist neither in `glyf` or `CFF `.

**Comment by drott** [comment]
FWIW, we use `SkScalerContext_FreeType::getBBoxForCurrentGlyph` to determine the size to allocate, which calls `FT_Outline_Get_CBox(&fFace->glyph->outline, bbox);` - so it's taking it from the glyph contour points in the `glyf` / `CFF /CFF2` tables - and I believe that's what we want. If the spec wording is not clear on it, we can clarify that.

> For COLR v0, advance width/height of the colour glyph must be that of the base glyph. This is stated in the current OT COLR spec, and in the draft in 5.7.11.1.8.1. The bounds for v0 formats aren't an issue since each glyph in each layer is drawn using it's glyf entry.

Side note: Contrary to that, for V0, I find that the Skia implementation actually computes the union of bounding boxes of all layers. May not be necessary and not 100% spec compliant but doesn't hurt much either, as in COLRv0 case, it's usually quick to compute the union as opposed to fully executing the graph.

> It should be possible to have contours consisting of a single point, but open contours exist neither in glyf or CFF .

This part I don't fully understand. Just, could you explain further what you mean?

**Comment by anthrotype** [comment]
> open contours exist neither in glyf or CFF .

yes, sorry, forget my mention about "open contour", I just meant single-point contours (which technically can't be either closed nor open)

**Comment by PeterConstable** [comment]
Addressed in PR #225
