### ISSUE TITLE
Sweep definitions consistency

### ISSUE THREAD

**Issue by drott** [googlefonts/colr-gradients-spec#250]
In PaintSweepGradient we have angles counterclockwise and y-axis plus as starting axis.

In CSS conic gradients it's y axis up, but angles clockwise.
In math, it's x axis plus as starting axis and angles counterclockwise.

My 2 cents 🪙: I think we should make it consistent with either CSS or math.

**Comment by anthrotype** [comment]
my 2cents go to math

**Comment by drott** [comment]
Also, I think we should specify whether the gradient should flip start and end if start > end and draw the shorter sector or if it should always draw the counterclockwise part.

**Comment by drott** [comment]
Also, do we really want to drop the meaning of padding here? It would be applicable, compare https://drafts.csswg.org/css-images-4/#repeating-gradients

**Comment by PeterConstable** [comment]
You have mentioned three distinct issues: angle direction, flip start/end, and extend modes.

**Angle direction**
Counter-clockwise was chosen to be consistent with the direction for angles in other parts of the OT spec:

https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_slnt
https://docs.microsoft.com/en-us/typography/opentype/spec/post

As for x- vs. y-axis, I chose y-axis to be consistent with CSS, but I don't have a strong preference: it's trivial to convert from one to the other.

**Flip**
Why would you want start and end to flip—what's the benefit? How would you obtain a gradient over the longer sector? If the angles vary in a variable font, would you want the direction of the gradient flip-flopping?

**Extending**
You mentioned padding, but the link you gave was for repeating, not padding. I assume you have all extend modes in mind. And if we were to support repeat similar to CSS repeating-conic-gradient, then presumably that would imply also allowing reflect and pad modes.

Because a sweep covers at most one full rotation, extending can only extend to at most one rotation. The effect of PAD can easily be achieved without the extend mode by defining a color line with [0,1] covering one revolution and adding two additional stops. Similarly, repeat and reflect can be achieved by adding a limited number of additional stops, though for these cases the extend modes would provide more convenience.

If (end - start) is not an integral factor of 360, then there will be a seam with partial repeat/reflect patterns on either side, and we'd need to specify where that seam occurs.

However, unless we were to add another extend mode, NONE, then we would lose the ability to define a gradient over less than one full rotation, as can be done in Skia. The effect could be achieved by adding stops with fully-transparent black, but it is a loss of convenience.

**Comment by PeterConstable** [comment]
Actually, wrt extend modes (repeating): what you suggest is already supported, without needing to change the current spec: 

>The color line may be defined using color stops outside the range [0, 1], and color stops outside the range [0, 1] can be used to interpolate color values within the range [0, 1], but only color values for the range [0, 1] are painted. If the specified color stops cover the entire [0, 1] range (or beyond), then the extend mode is not relevant and may be ignored. **If the specified color stops do not cover the entire [0, 1] range, the extend mode is used to determine color values for the remainder of that range.** For example, if a color line is specified with two color stops, red at stop offset 0.3 and yellow at stop offset 0.6, and the pad extend mode is specified, then the extend mode is used to derive color values from 0.0 to 0.3 (red), and from 0.6 to 1.0 (yellow).

So, to get an effect such as is shown at <https://drafts.csswg.org/css-images-4/#repeating-gradients>, just specify start and end angles to complete one full rotation, and define color stops over an integral fraction of the [0,1] range.

**Comment by drott** [comment]
My main intention was not to express personal preferences, but just clearing up some things that seemed hard to understand or ambiguous in our current definition while I was implementing that.

> **Angle direction**
> Counter-clockwise was chosen to be consistent with the direction for angles in other parts of the OT spec:
> 
> https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_slnt
> https://docs.microsoft.com/en-us/typography/opentype/spec/post
> 
> As for x- vs. y-axis, I chose y-axis to be consistent with CSS, but I don't have a strong preference: it's trivial to convert from one to the other.

In this case, I do have a mild preference for positive horizontal / x-axis as it would avoid one extra transform on the implementation side and it would be part of the same "mathematical" convention.

> **Flip**
> Why would you want start and end to flip—what's the benefit? How would you obtain a gradient over the longer sector? If the angles vary in a variable font, would you want the direction of the gradient flip-flopping?

I didn't say I want it that way. It was one aspect that I was struggling with when implementing this. Do we want the "flip" behaviour, or do we want the sector that follows "ascending" angles? Which part of our wording disambiguates which sector is to be drawn? To me it was not self-evident in which direction to draw the gradients.

We say:

> The color line progresses in the counter-clockwise direction; 

But perhaps we should emphasize that the counter-clockwise start to end sector is to be drawn, including the "zero/360 transition", i.e. drawing from 300 to 45 counter-clockwise. 

> Actually, wrt extend modes (repeating): what you suggest is already supported, without needing to change the current spec:

Looks like I didn't read the latest version. I see that the "newer" wording has explanations for this and allows extend modes. The [initial commit](https://github.com/googlefonts/colr-gradients-spec/pull/217/commits/ab4c43b9c387c933e83ee04f19bb403b2bad70c0#diff-f8c59e8d70f0a695574ea35269cf5f70c46db8cc40daa2d5e128e8c79be10528R519) had "In a conic gradient, the extend mode specified for the color line is ignored." and that was stuck in my head.

We do still have the wording at the end of 5.7.11.1.1:

> NOTE: Sweep gradients have special considerations in relation to color line extend modes and do not support repetition of gradient patterns. See 5.7.11.1.2.4 for details.

Which seems incorrect to me then - as repetition is supported, what do you think?

**Comment by PeterConstable** [comment]
>We do still have the wording at the end of 5.7.11.1.1...

Ah, I missed that. Thanks for catching.

**Comment by PeterConstable** [comment]
>Which part of our wording disambiguates which sector is to be drawn? 

I think that is made clear.

>The color line is aligned to a circular arc around the center point, with arbitrary radius, with stop offset 0 aligned with the starting angle, and stop offset 1 aligned with the ending angle. The color line progresses in the counter-clockwise direction; for example, if the start and end angles are both 0°, then stop offset 0.1 is at 36° counter-clockwise from the direction of the y-axis.

(y-axis will be changed to positive x-axis).

I could make this even clear by adding, "The color line progresses **from the start angle to the end angle** in the counter-clockwise direction..."

**Comment by drott** [comment]
Where I get stuck is: yes, the color line progresses in that direction, but we don't speak about the "drawn/filled pixels" area/sector explicitly. Theoretically, they could be separate things, which would be very meaningful but not an impossible interpretation.

Perhaps:

> Both the sector for which the gradient is drawn and the applied color line progress in the counter-clockwise direction; 

wdyt?

**Comment by PeterConstable** [comment]
I've added commits to #253 to change the 0 angle, and to clarify the painting.

**Comment by PeterConstable** [comment]
Btw, by changing the 0 angle, we may have ended up shifting the burden to convert from the runtime implementation to the authoring tool implementation (especially if conic/sweep gradients are [added to SVG](https://github.com/w3c/svgwg/issues/785)).

**Comment by PeterConstable** [comment]
#253 merged; closing.

**Comment by drott** [comment]
> Btw, by changing the 0 angle, we may have ended up shifting the burden to convert from the runtime implementation to the authoring tool implementation (especially if conic/sweep gradients are [added to SVG](https://github.com/w3c/svgwg/issues/785)).

Do you mean by avoiding one transform? I think at least for Skia we'll have one transform anyway to convert from clockwise to counterclockwise, so I think effectively the gradient computation and drawing has to go through a transformation matrix before and after.

**Comment by yisibl** [comment]
https://github.com/googlefonts/color-fonts/issues/44#issuecomment-826323719
