### ISSUE TITLE
handle degenerate linear gradient by using last color stop?

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/colr-gradients-spec#26]
the CORLv1 draft says

> If the dot-product (P₁ - P₀) . (P₂ - P₀) is zero (or near-zero for an implementation-defined definition) then gradient is ill-formed and nothing must be rendered

However, the SVG spec says that when the end points overlap, one should render as a solid paint with the last stop's color and opacity:

https://www.w3.org/TR/SVG/pservers.html#LinearGradientNotes

> If ‘x1’ = ‘x2’ and ‘y1’ = ‘y2’, then the area to be painted will be painted as a single color using the color and opacity of the last gradient stop.

Can we not do the same when P2-P0 vector is perpendicular to the P1-P0 vector?

**Comment by behdad** [comment]
You're right that our linear gradient is wrong. That is, it was written without padding on the two sides considered.  That's https://github.com/googlefonts/colr-gradients-spec/issues/25 to clean up.

This is what our degenerate handling should look like:

- If extend mode is _not_ pad, or if P₀ and P₂ are equal, then the entire gradient becomes a single color. Either use the color and opacity of the last gradient stop (matching SVG), or compute a weighted average color and opacity from the color line (my preference) if extend mode is _not_ pad, and average color and opacity of the first and last gradient stop if extend=pad but if P₀ and P₂ are equal,

- otherwise, if  (P₁ - P₀) . (P₂ - P₀) is zero, the gradient becomes two single-color half-planes, with P₀ on the boundary and (P₂ - P₀) normal to it. The half-plane that P₂ falls into should use the color and opacity of the last gradient stop while the other uses those from the first gradient stop.

**Comment by anthrotype** [comment]
> If extend mode is _not_ pad

why would the extend mode make a difference in the case of degenerate linear gradient?

**Comment by behdad** [comment]
> why would the extend mode make a difference in the case of degenerate linear gradient?

Because under extend=pad as you zoom out towards infinity the gradient becomes two colors, those of first and last stop. But if extend!=pad then the gradient cycles forever. As it becomes degenerate those colors just smudge and merge into one.

The only case that we are "giving up" is if P0==P2. In that case it's truly degenerate and there's no correct rendering. So maybe we should just say don't remember anything in that particular case.

**Comment by rsheeter** [comment]
Guiding principle: there shouldn't be sudden changes. Scaling down from <more than near zero> to <near zero> shouldn't have an abrupt shift, like suddenly not rendering.

**Comment by PeterConstable** [comment]
@anthrotype @drott @rsheeter Is there any outstanding issue here we need to address, e.g., if p1 = p0?

**Comment by PeterConstable** [comment]
We changed the way that a linear gradient is defined some time ago, per @220. With the new definition, the degenerate case wrt p2 is when p2 is colinear with p0p1.

The case called out in the SVG spec is when p0 = p1. For that case, we have said,

>If either point p₁ or p₂ is the same as point p₀, the gradient is ill-formed and
shall not be rendered.

It's been 8 months since there were any comments on that issue, and no comments on the above wording in the draft. So, assuming this can be closed.
