### ISSUE TITLE
Too many of your bytes are belong to us

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#298]
COLR is, if I may paraphrase Just lightly, provides a powerful structure but seems a bit airy, feels like it can be compacted more. #283 covers one specific possible path. Two more to explore, probably together:

1. Introduce a VarIdxMap (ala HVAR)
   * store a single VarId in the Paint graph and lookup VarId, VarId+1, etc in the map to get however many variation indices are needed.
   * VarIdxMap may achieve better packing than our current mandatory 4 byte per field VarWhatever types
1. Consider lower precision for specialized transforms
   * For example, to reuse a shape offset is rather fundamental, we immediately see *tons* of them when exploring variable COLR construction
       * We could amend PaintTranslate (or have a new Paint) that offers FWORD dx, dy and perhaps has the child Paint directly following (no Offset24). 5 bytes where today we spend 12.

Credit @behdad for both the initial ideas and this diagram to clarify them:

![image](https://user-images.githubusercontent.com/6466432/121291112-94183580-c89c-11eb-825e-e147ee1531a8.png)

I want to do some data gathering and if it looks promising I'll put up a PR for potential adjustments.

**Comment by behdad** [comment]
I'm still not happy with this. We're still trying to use VarStore for what it wasn't designed for (storage of tuples of variations). But I hope this extra VarIdxMap facility can save some of the pressure.

Looking at the CJK font we got, the biggest saving will come from using an FWORD PaintTranslate, which would also shrink the variations stored in the VarStore, and then the VarIdxMap can save bytes if we adjust the VarStore optimizer; that is, write a VarIdxMap-aware optimizer. Right now we don't have that. I'm thinking that through.

**Comment by justvanrossum** [comment]
Is the additional indirection via a VarIdxMap even necessary? This may be naïve, but I imagine a single "outer" index, and an incrementing sequence of "inner" indices.

**Comment by behdad** [comment]
> Is the additional indirection via a VarIdxMap even necessary?

Without it, all the variations within the same paint have to use the same outer index, which limits optimization opportunity. That said...

> This may be naïve, but I imagine a single "outer" index, and an incrementing sequence of "inner" indices.

This is exactly what it will boil down to when the optional `VarIdxMap` is not present.

**Comment by PeterConstable** [comment]
A variant of PaintTranslate with FWORD would be an easy addition and sounds likely to be useful: for comparison, composite glyphs in 'glyf' use FWORD to set a translation offset for the component glyph. (PaintTranslate vs. PaintShortTranslate? PaintTranslate vs. PaintTranslateShort? PaintTranslate (short) vs. PaintTranslateFixed?) 

But 'glyf' composites also allow for a byte (int8) as well. If there's a variant of PaintTranslate using FWORD, would it also be useful to have a variant that uses int8 values?

**Comment by behdad** [comment]
> A variant of PaintTranslate with FWORD would be an easy addition and sounds likely to be useful: for comparison, composite glyphs in 'glyf' use FWORD to set a translation offset for the component glyph. (PaintTranslate vs. PaintShortTranslate? PaintTranslate vs. PaintTranslateShort? PaintTranslate (short) vs. PaintTranslateFixed?)
> 
> But 'glyf' composites also allow for a byte (int8) as well. If there's a variant of PaintTranslate using FWORD, would it also be useful to have a variant that uses int8 values?

Rod and I were talking about the same. I think that works better in `glyf` table since such positions are relative. A byte position goes up to +128 only; that's hardly useful in any font with common UPEMs.

**Comment by rsheeter** [comment]
In our test font some PaintVarTranslate can be reduced to int8 but you can capture the majority of the value with just an int16 version.

**Comment by PeterConstable** [comment]
>In our test font some PaintVarTranslate can be reduced to int8 but you can capture the majority of the value with just an int16 version.

Sounds good.

**Comment by PeterConstable** [comment]
In HVAR, the index into the map was provided implicitly by gids. Here, there'd need to be a explicit field in the Var* structs to provide that index. So we're saving some bytes in one place (2 bytes in each Var* struct) but adding them in another (the DeltaSetIndexMap). Did this idea arise out of analysis of some existing prototype data that suggested there would be net savings?

I see +2 on [this comment](https://github.com/googlefonts/colr-gradients-spec/issues/298#issuecomment-857920814), but it's not clear to me what exactly y'all are converging on. Is it convergence to having mapping structures exactly the same as the DeltaSetIndexMap in [HVAR](https://docs.microsoft.com/en-us/typography/opentype/spec/hvar)?

If so, and if I'm understanding correctly, changes would be:
- Revise VarFword, etc., replacing the pair of uint16 fields (varOuterIndex, varInnerIndex), with a single uint16 field varIdxMapIndex
- append varIndexMapOffset to COLR v1
  - ignored if itemVariationStoreOffset is NULL
  - as with HVAR, may be NULL; if NULL, then outer index 0 is assumed, and the varIdxMapIndex in each Var* struct is interpreted as the inner index.
- Since DeltaSetIndexMap would now be used in both COLR and HVAR, it would make sense to move documentation of that out of HVAR into the variations common formats chapter.

Does that sound right?

**Comment by rsheeter** [comment]
> 2 bytes in each Var* struct

The theory is we'd save slightly more: you put one VarId on the whole structure and if you need multiple variation indices you use VarId+1,+2,...+N. Furthermore, the VarIdxMap may be able to represent the variation indices in less bytes as it has some smarts around compactness.

> Did this idea arise out of analysis of some existing prototype data that suggested there would be net savings?

Yes. For the lower precision transforms I was able to test it and observe it's efficacy. We can also see the overhead of Var* everywhere is not entirely trivial. The use of a VarIdxMap is as yet untested but it totally works on paper :D

**Comment by behdad** [comment]
Thanks Peter. The changes proposed are a bit more drastic:

> * Revise VarFword, etc., replacing the pair of uint16 fields (varOuterIndex, varInnerIndex), with a single uint16 field varIdxMapIndex
> * append varIndexMapOffset to COLR v1

The proposal is to remove VarFWORD etc, such that we _don't_ spend 4 bytes for variation of *each* item in a Paint. But add one  `VarId` (separate semantics from `VarIdx`) per paint. That then will attach consecutive `VarId`'s to all fields in the Paint that take variations...

If the `VarIdxMap` (aka `DeltaSetIndexMap`) is null, then the `VarId`s are interpretted as `VarIdx` and looked up in the `ItemVariationStore` directly. If `VarIdxMap` is present, then individual `VarId`'s are looked up in `VarIdxMap` to produce final `VarIdxMap` to look up in the `ItemVariationStore`.

>   * as with HVAR, may be NULL; if NULL, then outer index 0 is assumed, and the varIdxMapIndex in each Var* struct is interpreted as the inner index.

In the HVAR case, a major of 0 is assumed because number of glyphs is 16bit. For the proposed mechanism, that is not the case.

But... now I realize the `DeltaSetIndexMap` as defined in `HVAR` is limited to a 16bit count. So we need to use a flag there to allow 32bit item count as well. Oh well :(.

> * Since DeltaSetIndexMap would now be used in both COLR and HVAR, it would make sense to move documentation of that out of HVAR into the variations common formats chapter.

SGTM.

**Comment by behdad** [comment]
Basically the aim is to remove one 32bit `VarIdx` per possibly-variable item per Paint, but assuming consecutive `VarId`s. But to allow `ItemVariationStore` optimization, a non-direct mapping is optionally available via the `VarIdxMap` aka `DeltaSetIndexMap`.

**Comment by PeterConstable** [comment]
>The proposal is to remove VarFWORD etc... But add one VarId... per paint. That then will attach consecutive VarId's to all fields in the Paint...
> ... assuming consecutive VarIds.

If no VarFword etc., and if the VarId is set at the paint level, then in a PaintVarRadialGradient, then a single, sequential ordering would need to be assumed for:
- x0, y0, radius0
- x1, y1, radius1
- all of the stop offsets for the VarColorStops in the VarColorLine
- all of the alphas in the VarColorIndexes

(Actually, if we assume this is set only at the paint level, we could eliminate VarColorLine, VarColorStop and VarColorIndex. But that doesn't solve the above issue of determining a single, sequential ordering.)

Or, would we instead add a VarIdx to each relevant paint but also separately to ColorLine and to ColorStop? (That would solve the question of how items at these embedded levels interleave with the items at the paint level.)

**Comment by PeterConstable** [comment]
Separate question: would we add a varIdx field to all paints and eliminate the PaintX vs. PaintVarX distinctions? Or keep the PaintVar* tables and add that field only to those?

**Comment by rsheeter** [comment]
> would we add a varIdx field to all paints

I would think not; 4 bytes could be significant relative to some of the reduced forms. Imagine PaintTranslate, no offset, low precision.

**Comment by behdad** [comment]
> Or, would we instead add a VarIdx to each relevant paint but also separately to ColorLine and to ColorStop?

Correct. Every "table".

**Comment by behdad** [comment]
> > would we add a varIdx field to all paints
> 
> I would think not; 4 bytes could be significant relative to some of the reduced forms. Imagine PaintTranslate, no offset, low precision.

Right. Even with the offset, we are trimming down the non-variable translate to 8 bytes only. Would be a waste to force it to 12, specially given that the cost of extra paints is negligible in implementation.

**Comment by behdad** [comment]
> Would be a waste to force it to 12, specially given that the cost of extra paints is negligible in implementation.

Maybe a non-issue on bigger tables. We don't have to have same scheme for everything.

**Comment by behdad** [comment]
Another idea we should consider is moving the Transform into its own table so it can be shared by various PaintTransform's.

**Comment by rsheeter** [comment]
Changing Paint(Var)Location to have a sequence of offsets to coordinate (so they are shared on an individual basis) shows significant byte savings. Haven't had time to play with VarId / VarIdxMap yet.

**Comment by rsheeter** [comment]
We're basically out of time for v1, closing.

I expect we will have a v2 and, with any luck, a larger set of test fonts to inform future optimization. The main thing proposed here that was *not* done is to introduce a VarIdxMap and a single base identifier per table for variation values (as opposed to every field having it's own).

**Comment by rsheeter** [comment]
Oops, didn't realize @PeterConstable was still planning to look at this. Reopening!

**Comment by PeterConstable** [comment]
There were two suggestions, both of which have been implemented in the spec:

1. use VarIdxMap (i.e., a DeltaSetIndexMap) rather than VarFWord, etc.: implemented in #316 
2. use lower precision (F2DOT14 rather than Fixed) for various transforms: implemented in #307, #310, #313
