### ISSUE TITLE
Multi-layer opacity

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#32]
Compiling vector graphic sources, such as svgs, to COLR fonts will be significant to icon and emoji use cases (twemoji, noto emoji, and others come to mind). SVG allows application of opacity to multiple layers at once (by setting opacity on a group), meaning effectively render the group then apply opacity to the end result, as I understand it.

The current COLR spec doesn't allow for this. Building equivalent stacks of individually layers with opacity to match a group of layers with opacity appears tiresome. Also, when I tried to construct equivalent individual layers to a simple group opacity setup (courtesy of @anthrotype) by hand I immediately ran into halo effects (from anti-aliasing?). 

Off the top of my head there are three main options

1. Use some 2D graphics technique I'm unaware of to build equivalent single layers to match the group w/o introducing artifacts. Hooray, there is no actual problem :)
1. Add the ability to designate groups of layers with opacity to COLR
1. Accept that this is not supported by COLR; the set of things we can represent in COLR just got smaller

**Comment by davelab6** [comment]
For (1) I'm confused about where the grouping metadata lives, to pass to the 32 graphics engine. 

That seems to be (2), no?

**Comment by bungeman** [comment]
I sounds like what you want is a component COLR glyph where the glyph representation is a list of COLR glyphs to draw (from back to front) each with an alpha. Unfortunately the existing component flag doesn't seems to have enough bits to just shove an alpha in there, though maybe it could have a flag to indicate that there is an alpha to apply if the component glyph is being drawn with COLR (of course, I'm not sure how component glyphs and COLR work together in practice at the moment).

**Comment by bungeman** [comment]
I went and modified a little test COLR font I have to make a component glyph where each component was a glyph id with a COLR entry. As I expected components were the regular glyf outlines and not the COLR versions (tested with FreeType, macOS 10.15, Windows 10 in IE11). It would actually be a little confusing from an implementation standpoint otherwise. When evaluating a glyf for outlines the component should go together as it always has. (Just because a glyf component has ids which have COLR entries doesn't mean they should be in color since the fact that glyf entries can be component is just an implementation detail.)

It does seem a little unfortunate that there isn't really an component analog for COLR glyphs. I suppose the idea was that it should just be possible to re-use base glyf by reference (so in theory you only need one glyf umlaut and can use it with different COLR glyphs) but this doesn't handle the additional translation / attachment points, advance with override, or 2x2 matrix, etc (a multi-colored umlaut which wants to be attached to a particular point, also a re-usable group is a nice thing to have available for multi-person emoji, etc) and of course alpha.

I suppose the biggest difference with component glyf and component COLR glyphs with alpha would be that a component glyf can always be expanded (it's just a compression scheme) but component COLR glyphs with alpha cannot (there is a difference between drawing each contour with alpha and drawing a set of contours opaquely together and then compositing them with alpha).

**Comment by rsheeter** [comment]
@davelab6 in #1 the idea is you eliminate the need for grouping, you have an algorithm to create equivalent ungrouped layers.

A color layer that references a component-based glyph assigns the whole thing a single paint so I think that doesn't quite work. Imagine you want two overlapping boxes with two different colors, and to make the final result transparent. You could make a component with the two boxes and a COLR layer that referenced that component ... but they'd get the same paint so the different colors would be awkward. 

https://github.com/googlefonts/picosvg/issues/78 has a couple of examples. Ignore the picosvg output, just consider the original/input.

If there was a grouping construct with it's own opacity between BaseGlyphV1Record and LayerV1Record you could express render layers 1,2,3 and then make the entire group 50% opacity. Not necessarily suggesting that, just trying to illustrate the type of thing that causes a problem.

**Comment by PeterConstable** [comment]
#13 may be relevant for this: I suggesting the possibility of adding a flags field which might be used for various things one being to allow for different blend modes. Behdad responded with a link to doc'n on Cairo operators, that might allow for this. But another possibility would be a flag to indicate a grouping (layers with bit n set are part of the same group as the immediately-preceding layer; the first layer in the group would have the bit clear).

**Comment by PeterConstable** [comment]
Further thought: If alpha (/opacity) were an attribute of LayerV1Record rather than (or in addition to?) ColorIndexRecord, and if LayerV1Record included a flags field with a grouping bit, then it would be possible to specify a contiguous set of layers as a group and have the first layer in the group not have any paint offset of its own but simply specify the alpha for the group as a whole (and perhaps set other blend-related flags).

**Comment by rsheeter** [comment]
LayerV1Record having alpha, flags, and blend mode sounds like it accommodates all my needs. I see two downsides to this approach (not necessarily deal breakers):

1. Wasted bytes when you don't need a group or a layer alpha
   - I believe most layers in Noto Emoji and Twemoji wouldn't use group or layer alpha ... but they would pay filesize
1. Introduction of multiple ways to specify the same thing
   - Do I set the ColorIndex alpha or the LayerV1Record alpha for a non-group layer?

To throw an alternative out, what if we added a vector of groups to the base, thereby eliminating the per-layer tax? - sketch:

```C++
// NOTE: I'm assuming we add blendMode to the LayerV1Record [or Paint?].

struct GroupV1Record
{
  uint32          groupStart;  // first layer in group
  uint32          groupEnd;    // last layer in group, must be at least start + 1 (no single layer groups)
  VarF2DOT14      alpha;
  uint8           groupBlendMode;
};

typedef ArrayOf<GroupV1Record, uint32> GroupV1List;

struct BaseGlyphV1Record
{
  uint16                gid;
  Offset32<LayerV1List> layers;
  // groups cannot overlap and are ordered by groupStart
  // standalone layers shall not have a group
  Offset32<GroupV1List> groups;
};
```

Curious what @behdad, @drott, @anthrotype  think?

**Comment by drott** [comment]
The current implementation principle is an iteration over the layers, retrieving their colorline's etc and paints them with srcover one by one, (btw. [Skia blend modes here](https://source.chromium.org/chromium/chromium/src/+/master:third_party/skia/include/core/SkBlendMode.h;l=13?q=SkBlendMode&ss=chromium%2Fchromium%2Fsrc))

From an implementation point of view, flags on each layer could be retrieved in this loop, upgrading to a layer, or flushing a layer, whenever the flag changes and determines establishing a new layer or a layer flush.

The parallel groups structure would work as well: in the layer loop, I could check in parallel whether this current layer needs to open/establish a new grouping layer, and which blend mode is applied, when it is closed, after `groupEnd` and this still has linear complexity if the constraints are kept, i.e. the layer starts and ends are monotonically increasing. 

I am wondering if there is a risk that a font is published that does not follow the ordering constraints and one implementation will support that, another won't, then to support this we'd have to search through all groups which makes it O(n^2) complexity - if it was in flags on the layers, this would probably be avoided but perhaps makes the format more complicated to understand?

I did look at `SkCanvas` API for implementing that (bungeman@, please let me know if that sounds about right): and I can upgrade to a new layer by using `int saveLayer(const SkRect* bounds, const SkPaint* paint);`
and setting an SkPaint with corresponding `setBlendMode()` and `setAlpha()` - then when the group ends, call `restore()` to paint the layer given the `alpha` and `groupBlendMode`.

**Comment by bungeman** [comment]
If it is decided to do something like `GroupV1Record`, I would reiterated my earlier suggestion to also allow what component glyphs currently allow, which it to say allow an optional attachment point (translate this group so point x of this group lines up with point y of everything preceding) and an optional extra translation, scale, or 2x2 matrix. (Note that use_my_metrics seems problematic due to needing to use the same metrics as the underlying original glyph.) This is in addition to specifying the alpha and blend mode for the whole group.

As far as blend modes, basically everyone supports the basic porter-duff blend modes (everything down to kLastCoeffMode in the [Skia blend modes](https://source.chromium.org/chromium/chromium/src/+/master:third_party/skia/include/core/SkBlendMode.h;l=13?q=SkBlendMode&ss=chromium%2Fchromium%2Fsrc)). I'd have to check but that list pretty much lines up with what SVG does. [D2D](https://docs.microsoft.com/en-us/windows/win32/api/d2d1_1/ne-d2d1_1-d2d1_composite_mode) seems to not support all of them for some reason and [CoreGraphics](https://developer.apple.com/documentation/coregraphics/cgblendmode?language=objc) seems to do all of them. May want to take the intersection of these. Note that the 'clear' blend mode satisfies the general desire for the 'punch a hole' operation.

The summary of how this works in Skia in the above comment is accurate, and should be fairly similar on all platforms. As far as fonts with a `groupStart` or `groupEnd` which are somehow invalid (wrong order, out of bounds, not monotonic) I would suggest that implementations either ignore the group (still do the layers but they just aren't treated as a group) or just declare the entire color glyph malformed and not use the color version. So long as no implementation actually tries to fix it up (as was done with cmaps which aren't in order) such issues should hopefully not proliferate. Or of course someone could come up with an encoding which is both difficult to get wrong but also compact, but I currently can't think of anything off the top of my head.

**Comment by PeterConstable** [comment]
Adding an idea in line with this topic: I think it could be very useful, from a design perspective, to be able create alpha-channel gradients. In terms of the model of the current proposal, this would be like a layer that can have a linear or conical/radial gradient that is providing a gradation of opacities for layers (or group of layers) above it.

**Comment by behdad** [comment]
I suggest we add alpha to the layer record and have a way to say referenced layer should be looked up from COLR table. Basically similar to what @bungeman suggested. Let me make a concrete recommendation.

**Comment by behdad** [comment]
```
struct PaintGroup
{
  uint16 format; // = 4
  VarF2DOT14 alpha;
};
```

This paint is different in that it implies the layer `gid` should be rendered using `COLR` table itself, then alpha applied to it,

Separately, excuse me for saying here:

I'm *very* included to suggest adding a translation (x/y offset) to layers. That would immensely help... I've been meaning to open an issue for that. Rod pointed this out to me in June and I haven't got time to write it yet. Imagine a clock face, with 12 dots. Without gradients, the 12 dots could be in one layer glyph and painted. With gradients, since each layer can have one gradient only, one would need 12 different gid's one for each dot... If we add layer translation the same dot can be positioned 12 times. Let me know if I should suggest a change for this.

**Comment by behdad** [comment]
Same `PaintGroup` can have an optional offset to `Affine`. That's what I recommend. Then one can have one dot gid, add a gradient to it in COLR table once (using its own gid referring to itself), then 12 types paint it using the newly proposed `PaintGroup`.

**Comment by rsheeter** [comment]
❤️🎨 (closest I could find to a group of paints)

**Comment by davelab6** [comment]
Translation sounds great. Would it include scale and shear like glyf components? And wouldn't include rotation?

**Comment by PeterConstable** [comment]
A 2x2 allows for scale, shear and rotation. A 2x3 allows for that plus translation.

**Comment by rsheeter** [comment]
I believe we want 2x3 and have sketched it so in #34.

**Comment by PeterConstable** [comment]
>D2D seems to not support all of them for some reason and CoreGraphics seems to do all of them. May want to take the intersection of these.

Unless Microsoft pushes back for some reason, I wouldn't assume that D2D limitations need to constrain. They will need to do D2D work to support COLRv1 regardless since D2D's radial gradient is really a radial gradient, in the strict sense, and not a conical-radial (cylindrical, really) gradient as proposed here.

**Comment by behdad** [comment]
Alpha-channel gradient, ie. masks, it's interesting. Let me see if I can suggest blend-modes, masks, and clipping.

**Comment by PeterConstable** [comment]
*Mentioning so that design alternatives are considered (and duly ruled out).*

>Wasted bytes when you don't need a group or a layer alpha

This got me wondering if a organization analogous to Feature tables and LookupList in GPOS/GSUB might provide some efficiency benefit. The idea would be that there would be *one* LayerV1List for the COLR table rather than a separate LayerV1List per base glyph. Then the BaseGlyphV1List has base glyph tables that each have an array of indices into the LayerV1List.

That would allow re-use of layer definitions (LayerV1Record). 

But I don't know that would save much or at all (and it might regress): It would add a 32-bit index every time a layer is used for some base glyph.

**Comment by rsheeter** [comment]
Closing for now as we've resolved OP issue but please reopen as needed. I suggest we pursue blendmodes, masks, and perhaps clipping on #13.

**Comment by behdad** [comment]
> Alpha-channel gradient, ie. masks, it's interesting. Let me see if I can suggest blend-modes, masks, and clipping.

This is now being discussed in https://github.com/googlefonts/colr-gradients-spec/pull/35
