### ISSUE TITLE
Should format 3 support two transforms?

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#41]
Currently, there's one Affine2x2 for both circles. That allows the cylinder defined by the two circles to be uniformly elliptical. But conceptually it would be possible to have a cylinder defined by two separately-transformed circles.

Adding a second offset field could allow separate transforms for start and end circles. If one offset is null, the same transform could be applied to both.

Thoughts?

**Comment by rsheeter** [comment]
@drott @bungeman curious if this idea presents implementation concerns as I believe the current structure was chosen specifically to avoid them?

**Comment by rsheeter** [comment]
Per IM discussion this appears to be be due to implementations not supporting it. We have tried throughout to avoid constructs that are not widely available even if they make sense in abstract. I think that means we can actually go the other way (as suggested in #45) and delete the 2x2 from radial entirely.

Closing but as always please reopen as needed.
