### ISSUE TITLE
Necessarity of PaintColrGlyph (paint format 7)

### ISSUE THREAD

**Issue by reli-msft** [googlefonts/colr-gradients-spec#51]
From the draft I read, it looks like that, this format is created only for sharing data across glyphs. However, since paints are referenced with offsets, it is simple to reuse the same paint for multiple glyphs / upper-layer paints, by pointing the offsets to the same target.

So should we either remove this format, or specify that using a `PaintColrGlyph` instead of just stretching the offsets do _carry_ semantics, and they are semantically different, even if they are visually the same?

**Comment by rsheeter** [comment]
I think perhaps the nuance I would add is that it's meant for *efficient* sharing. It allows you to reuse an entire COLR glyph - made up of many paints - rather than having to reuse paint by paint.  A COLR v1 compiler can take advantage of this to do things like express each # o`clock emoji as:

1. PaintColrGlyph: the entire backdrop, multiple painted layers
1. PaintTransformed: rotate the hour hand into position

https://github.com/googlefonts/colr-gradients-spec/blob/master/colr-gradients-spec.md#reusable-parts illustrates the clock example.

Reuse of sets of parts shows up all over emoji, one of the major use cases for COLR:
<img width="955" alt="Screen Shot 2020-09-28 at 7 04 41 PM" src="https://user-images.githubusercontent.com/6466432/94505109-31c04e80-01bf-11eb-8bfe-42a23881e6a5.png">

Could you please expand on what you mean by this:

> [...], or specify that using a `PaintColrGlyph` instead of just stretching the offsets do _carry_ semantics, and they are semantically different, even if they are visually the same?

**Comment by behdad** [comment]
I'll comment by tomorrow. I have a point to offer.

**Comment by reli-msft** [comment]
@rsheeter The sentence I said is to ask about whether `PaintColrGlyph` carry significant semantic difference beyond sharing (possibly multiple) paints. It looks like everything that a `PaintColrGlyph` could do can be expressed with sharing trees of `PaintComposite`s across glyphs. Although, using a `PaintColrGlyph` looks more efficient.

**Comment by rsheeter** [comment]
> It looks like everything that a PaintColrGlyph could do can be expressed with sharing trees of PaintComposites across glyphs. Although, using a PaintColrGlyph looks more efficient.

Agreed on both points :) I think the efficient aspect justifies the format.

**Comment by reli-msft** [comment]
@rsheeter It may worth adding a note about that, all `PaintColrGlyph`s could be equivalently unfolded into a tree of `PaintComposite`s, and vice versa.

**Comment by PeterConstable** [comment]
I had a comment related to this in another issue. It's not clear how (i) using a PaintColrGlyph would be any different than (ii) using a PaintTransform with a transform matrix of (1, 0, 0, 1, 0, 0), except that (i) consumes a glyph ID, while (ii) requires the shared paint to come later in the table than everything that uses it. Aside from tradeoff of glyph IDs vs. offsets, I don't see how there'd be any semantic difference, or any efficiency difference.

There might be some _convenience_ for designers and tools, though.

**Comment by behdad** [comment]
That's the most nonsense I've heard in a while.

**Comment by PeterConstable** [comment]
Then please explain what can be done using PaintColrGlyph that could not also be done using PaintTransformed?
