### ISSUE TITLE
Clarify PaintFilledGlyph

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#60]
It's clearly misleading; it clips not fills. `PaintClipGlyph`?

Explain nesting of clips == intersection

**Comment by rsheeter** [comment]
Helps #54

**Comment by behdad** [comment]
It fills the glyph outline with paint. I don't see any problem.

True bikeshedding. That's why we should have just kept it as PaintGlyph. Sigh

**Comment by PeterConstable** [comment]
Suggestion: PaintGlyphOutlineClip

**Comment by behdad** [comment]
Just argh...

**Comment by PeterConstable** [comment]
Didn't notice `PaintClipGlyph`. That works.

**Comment by behdad** [comment]
`PaintClipGlyph` is the most bizarre naming.

Please remove my name from this proposal. This is not what I envisioned anymore.

**Comment by alerque** [comment]
Reading the before and after from 6d46c32 along with descriptions of each I have to agree with @behdad here that the original pair of `PaintGlyph` and `PaintColrGlyph` was clearer and more to the point. The confusion pointed out in this issue as originally opened was only brought on by the change from `PaintGlyph`→`PaintFilledGlyph`, and I think `PaintClipGlyph` just muddies the waters more.

**Comment by rsheeter** [comment]
Ignoring the name for the moment, I think there is a fair criticism that how things combine was not clear. If you think of PaintGlyph (by any name :) as a clip then the result of PaintGlyph nesting another PaintGlyph is obvious. If you think of it as a fill ... possibly less clear.

> The confusion pointed out in this issue as originally opened was only brought on by the change from PaintGlyph→PaintFilledGlyph, and I think PaintClipGlyph just muddies the waters more.

I think I agree and that I should just reverse that change

**Comment by behdad** [comment]
> Ignoring the name for the moment, I think there is a fair criticism that how things combine was not clear.

That's not the point of a file format specification though. You or Peter can write blogposts about how things are expected to work together. The font format is not room for Peter's ruminations of his limited understanding of how things are supposed to work.

cc @simoncozens @alerque

**Comment by rsheeter** [comment]
My inclination at this point is to go back to the name `PaintGlyph` and add (or restore, I think I actually had it at one point) a note that what it does is clip the paint it references. 

> That's not the point of a file format specification though

There is value in some degree of explanation of how to use the format. That explanation should fit the audience, we can err in providing too much or too little detail.

We offer explanations of boundedness, illustration of gradients, ... I guess I don't understand why clarifying the behavior of one of the formats is across the line? - I can tell you as a reader I would find that clarification useful.

> his limited understanding

At risk of being accused of being the tone police, I would request we avoid ad hominem attacks.

**Comment by alerque** [comment]
This is wandering from the topic of this issue, but the way this and other issues are cropping up does highlight a significant procedural weak link in the current process. This repo has quite a bit of history showing how the technical details of this proposal were refined. It doesn't start from the grass roots and it has gaps along the way (presumably where work and discussion happened elsewhere, offline, in video, etc. along the way). That's all fine and expected, but even as a complete outsider to the COLR issue in general and this proposal in specific I am able to make out not only what the latest technical contribution towards a spec is but follow some of the reasoning of how it got to be that way.

Skip ahead to the PDF documents that landed in the MPEG-OTSPEC list and there is a huge disconnect. I understand the ISO process requires proposals to be in a different format and include things that are not part of this technical work, but **there should not be a black box process that editorializes technical content**. Inevitably some editorial work is necessary I understand, but there is no reason that work shouldn't be exposed using the same history mechanism. It shouldn't take such a huge effort for people to comb through the OFF proposal documents line by line manually looking for how they changed from this technical input proposal. There shouldn't be a private repo where the source documents are being worked on that the authors of these technical specs can't follow along, `diff` between whatever points they want to check, and overall verify the integrity of the technical aspects as the work to massage it into an ISO spec addendum progresses.

There are surely other ways, but here's one way it might work technically to bridge the gap between these MD sources and the DOCX output required by ISO as input:

* A fork (or branch) can be made of this repository
* All the copy-editing that is deemed necessary can be done directly in Markdown
* All the re-arranging sections to fit the required output format can be done in Markdown
* Any extra bits that need to be added but have technical ramifications can be done in Markdown
* The fork/branch can be frequently rebased to keep all commits *in this order* so that the copy-editing bits can potentially be merged back upstream into this repository while keeping the ISO proposal specific rearrangement / expansions separate.
* The result of that process can be converted (Pandoc or similar) to a Word doc, or even just copy pasted into a Word doc. That document can also be committed to the fork/branch, but keep commits to it separate from commits to Markdown sources.
* As work to format the Word doc progresses, the text of the Word doc can be dumped back to plain text or Markdown. This result can be diffed with a dump of the Markdown sources at the tip of the same branch to verify that no content changes are introduced and nothing is missing.

The tooling for this is not hard to setup, and the result of such a process would be a complete paper trail for the editorial process which could be easily reviewed both by contributors from both ends of the process.

**Comment by simoncozens** [comment]
A simpler way to do steps 1-4 would have been to write the proposal as a pull request here.

It's important to note, however, that the proposal submitted to the OFF AHG is intended (as Vlad has carefully explained on the mailing list) to be a *starting point* just to get consensus on the concept of commissioning an official work item which, if approved, then gets technically reviewed by the AHG, finalized into an amendment, which then goes to national balloting which (phew) *eventually* changes the OFF spec. (ISO is hilarious.)

As I understand it, because of the timing of meetings and balloting processes, getting *something* (even if incomplete and inaccurate and with outstanding questions) to AHG to kick off the work item process before the next meeting deadline was worth doing, on the basis that things can get fixed up later. So what Peter has posted is not the final submission to ISO and @behdad does not need to be tearing his hair out just yet. (Although of course what goes into the first proposal is more than "hey, how about this for an idea?" - it is naturally considered the baseline that then gets refined, so there is some responsibility to get it right...)

I think the main thing that you are asking is for Peter to change his way of operating from a "closed source" model (take the text from this repo, go away and do stuff, and then literally release compiled binaries!) to developing submissions in the open, showing his working in a way that others can monitor, provide contemporaneous feedback, and collaborate on. I think this makes a huge amount of sense, would be beneficial to all parties, and would lead to a much better output - but it's not something we can easily mandate; and at any rate, established working patterns are hard to change. Perhaps next time, when specifications are commissioned, those doing the commissioning need to be somewhat more prescriptive about the process by which they expect them to be developed.

**Comment by alerque** [comment]
Composing an ISO proposal in a PR would provide a much easier feedback mechanism and review process, but it wouldn't fully connect the dots as far as a `diff`able history from the technical groundwork to the content of the proposal. Unless of course you just mean PR'ing the commit series I mentioned and the final state of this repo *being* the proposal. If that was the goal then sure it would be simpler not to have two separate end results that needed comparing. My offering was a way to keep both technical groundwork and resulting formal proposal content separate but diffable. However that's a minor detail and I agree fully with the rest of what you said @simoncozens.

* Yes it is good that a preliminary proposal was made so that the long-running machinery needed starts spining up. I understand the need for approval of a work item even without a finished proposal. I am not objecting to that.

* I'm not even saying this proposal has to start over, but in moving the draft to final proposal it may still be helpful to use at least some of these steps.

* Yes anybody commissioning work like this should mandate a better process, but it's even hard to expect that if we don't start demonstrating that a better process even exists. I know it's hard for established workflows like ISO & M$ corporate culture to shift gears, hence why I keep trying to document specific alternative steps that would be actually open.

**Comment by rsheeter** [comment]
Zooming out from the current issue, part of what I expect to get our of COLR v1 is an improved understanding of how to approach font spec changes.

@simoncozens I'm with you on pushing toward developing the font spec in the open. We didn't achieve that here. We'll try to do better in future.

> the final state of this repo being the proposal

I aspire to move closer to that over time. It is not clear to me whether we can fully reach that state but we can definitely get closer.

Short-term we are going to attempt to make the proposal in this repo much more similar to what goes to the AHG (and perhaps WG3). This has begun in #62.

**Comment by behdad** [comment]
> So what Peter has posted is not the final submission to ISO and @behdad does not need to be tearing his hair out just yet.

That's ignoring my main issue: Peter should NOT change the technical content of the proposal, no matter what. He has shown a sustained record of doing that for years and using his power as the only person who has the pen to push his personal thinking over what the technical experts designed and agreed on.

How can I get that issue discussed and addressed?

That the proposal was made not in the open is another issue, yes.

**Comment by behdad** [comment]
> I think there is a fair criticism that how things combine was not clear.

To whom? To someone without any engineering or graphics-system experience? Because it was / is fully clear to anyone who has some relevant experience.

**Comment by rsheeter** [comment]
We are actively trying to figure out how to minimize non-public edits. IIUC ISO does want a docx at some point. I don't think we can alter ISO process quickly. If we structure the public copy appropriately I'm optimistic that docx can basically == public content. I want to find out if we can publish the docx we submit to ISO on GH under an open license. 

> > I think there is a fair criticism that how things combine was not clear.
> 
> To whom? To someone without any engineering or graphics-system experience? Because it was / is fully clear to anyone who has some relevant experience.

I claim some eng but no graphics experience and would have appreciated a note about clip. It hit me when wondering what PaintGlyph>PaintGlyph should do. IIRC I reached the right conclusion but a note about clip would have gotten me there faster.

**Comment by rsheeter** [comment]
#73 enumerates what I currently understand to to be needed for an "in the open" ISO submission
