### ISSUE TITLE
Why bother with P2 in PaintLinearGradient?

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#94]
IIUC, the effect of having P2 not the same as P1 could easily be achieved by changing the placement of P1. So, is there really any benefit of keeping P2?

**Comment by drott** [comment]
The background here has been to be able to apply variations to P2 independent of P1 in order to clamp the gradient transformation to another coordinate or to other parts of the glyph shape. 

This still has limits as to on what trajectories P2 can "travel", but it gives more flexibility than connecting the gradient to to P1 alone.

**Comment by PeterConstable** [comment]
The effect of applying variation to the position of P2 could also be achieved (without separate P2) by varying the position of P1, and wouldn't have the risk of P0P1 · P0P2 = 0.
